### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tizianatocci**
readme.md file updated concerning the CellHunter+ part

### CODE REVIEW

**Comment by franck-simon** [comment]
Sorry, some remarks : 
- CellHunterPlus+ => CellHunter+
- beware => be aware
- could slightly changed => could slightly change 
- videos' path => video's path ?
- the number of frame. => the number of frames. 
- will likely different => will likely be different
- the parameters set are => the parameters set is or the parameters are
- "1. The first parameter ... be set to "dark". Concerning the immune" should be splitted
   => 1. The first parameter ... be set to "dark". _newline_
        Concerning the immune cells, the parameters set is:  _newline_
        2.  r_sp, the theoretical radius
    or alternative way, remove "Concerning the immune cells, the parameters set are:"
 - immune cells’ trajectories
 - "less immune cells are considered. Concerning the cancer cells, the parameters" to be splitted on two lines 
- "centre of the ROI. As example, " : same should be splitted on two lines

**Review by franck-simon — APPROVED** [review]
You have still commas here that I guess should be removed, no ? 
videos' path
immune cells’ trajectories

**Comment by tizianatocci** [comment]
Thank you and sorry
Concerning the two specific remarks:
•	videos' path => video's path - Here I left videos’ path because it is actually more than one roi
•	immune cells’ trajectories  - Here I wanted to leave the plural as well but maybe I missed the remark

**Comment by tizianatocci** [comment]
In the end I deleted the apostrophes

**Pull request merged**
